CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=80000

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# ST7789V Settings
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
# CONFIG_ZMK_DISPLAY_INVERT=y
# CONFIG_ST7789V=y
# CONFIG_ST7789V_RGB565=y

# Prospector Settings
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=y